{% set name = "gmake" %}
{% set version = "4.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: .

build:
  number: 0
  skip: True  # [not win]

requirements:
  build:
    - vs2022_win-64
    - symlink-exe-build
  run:
    - make

about:
  home: https://www.gnu.org/software/make/
  license: GPL-3.0-or-later
  summary: >-
    GNU Make is a tool which controls the generation of executables and other non-source files of a program from the program's source files.
  doc_url: https://www.gnu.org/software/make/manual/

extra:
  recipe-maintainers:
    - feng1m8
