{% set name = "chealpix" %}
{% set version = "3.30.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/healpix/files/Healpix_3.30/{{ name }}-{{ version }}.tar.gz
  sha256: dbc5ba0d84d6e5f69bdffe6eb572c206e8fefd5bb187d52bbf9b2763b636dbd7
  patches:
    - Fix_link_on_windows.patch  # [win]

build:
  number: 0
  skip: True  # [not win]
  ignore_run_exports:
    - vc  # [win]
    - ucrt  # [win]

requirements:
  build:
    - vs_win-64
    - autotools_clang_conda
    - m2-pkg-config
  host:
    - cfitsio
  run:
    - cfitsio

about:
  home: https://sourceforge.net/projects/healpix/
  doc_url: http://healpix.sf.net/documentation.php
  dev_url: https://sourceforge.net/projects/healpix/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file:
    - {{ BUILD_PREFIX }}/Library/usr/share/automake-1.9/COPYING
  summary: Software for pixelization, hierarchical indexation, synthesis, analysis, and visualization of data on the sphere.
  description: |
    HEALPix is a Hierarchical, Equal Area, and iso-Latitude Pixelation of
    the sphere designed to support efficiently (1) local operations on the
    pixel set, (2) a hierarchical tree structure for multi-resolution
    applications, and (3) the global Fast Spherical Harmonic transform.
    HEALPix based mathematical software meets the challenges presented 
    by high resolution and large volume data sets, such as the WMAP and
    Planck CMB mission products.
