{% set name = "cfitsio-static" %}
{% set version = "4.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: .

build:
  number: 0
  script: python build.py
  skip: True  # [not win]

requirements:
  build:
    - conan
  run:
    - cfitsio {{ version }}
  run_constrained:
    - zlib 1.3.*

about:
  home: http://heasarc.gsfc.nasa.gov/fitsio/fitsio.html
  license: NASA-1.3
  license_file: licenses/NASA_Open_Source_Agreement_1.3.txt
  summary: A library for reading and writing FITS files
  description: |
    CFITSIO is a library of C and Fortran subroutines for reading and writing
    data files in FITS (Flexible Image Transport System) data format. CFITSIO
    provides simple high-level routines for reading and writing FITS files that
    insulate the programmer from the internal complexities of the FITS format.
    CFITSIO also provides many advanced features for manipulating and filtering
    the information in FITS files.
  doc_url: https://heasarc.gsfc.nasa.gov/docs/software/fitsio/quick/quick.html

extra:
  recipe-maintainers:
    - feng1m8
