{% set name = "relxill" %}
{% set version = "2.3.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/thdauser/relxill.git
  git_depth: 1

build:
  number: 2
  skip: True  # [not win]
  ignore_run_exports:
    - vc14_runtime
    - ucrt
    - vc
    - python_abi
    - fftw
    - cfitsio

requirements:
  build:
    - git
    - clangxx_win-64
    - vs2022_win-64
    - cmake
    - ninja
    - python
    - fftw
    - cfitsio
  run:
    - fftw
    - cfitsio

about:
  home: https://www.sternwarte.uni-erlangen.de/~dauser/research/relxill/
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: X-ray Astrophysics local model for Relativistic Reflection
  description: relxill is a new reflection model, which can be readily used in common X-ray data analysis tools such as isis, xspec, or sherpa. It combines the xillver reflection code and the relline ray tracing code. The striking feature is that for each point on the disk the proper xillver-reflection spectrum is chosen for each relativistically calculated emission angle.

extra:
  recipe-maintainers:
    - feng1m8
