{% set name = "aria2" %}
{% set version = "1.37.0" %}
{% set sha256 = "67d015301eef0b612191212d564c5bb0a14b5b9c4796b76454276a4d28d9b288" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/releases/download/release-{{ version }}/{{ name }}-{{ version }}-win-64bit-build1.zip
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not win]

about:
  home: https://aria2.github.io/
  summary: aria2 is a lightweight multi-protocol & multi-source, cross platform download utility operated in command-line. It supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink.
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  dev_url: https://github.com/aria2/aria2/

extra:
  recipe-maintainers:
    - feng1m8
