{% set name = "perl-xml-libxslt" %}
{% set version = "2.003000" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-LibXSLT-{{ version }}.tar.gz
  sha256: 7caa5aee72f53be59d8b84eecb6864a07c612a12ea6b27d5c706960edcd54587

build:
  number: 0
  skip: true  # [not win]

requirements:
  build:
    - perl 5.32.*
    - make
    - feng1m8::m2-pacman
  run:
    - perl 5.32.*
    - perl-xml-libxml 2.0209

outputs:
  - name: {{ name }}
    files:
      include:
        - Library/site

about:
  home: https://metacpan.org/dist/XML-LibXSLT
  license: Artistic-1.0-Perl OR GPL-1.0-or-later
  # license_file:
  #   - licenses/perl/Artistic
  #   - licenses/perl/Copying
  summary: Interface to GNOME libxslt library

extra:
  recipe-maintainers:
    - feng1m8
