{% set name = "ccfits" %}
{% set version = "2.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/{{ name }}/CCfits-{{ version }}.tar.gz
  sha256: f63546d2feecbf732cc08aaaa80a2eb5334ada37fb2530181b7363a5dbdeb01a

build:
  number: 0
  skip: True  # [not win]
  ignore_run_exports:
    - ucrt  # [win]
    - vc  # [win]
    - vc14_runtime  # [win]

requirements:
  build:
    - vs_win-64
    - autotools_clang_conda
  host:
    - cfitsio
  run:
    - cfitsio

about:
  summary: CCfits is an object oriented interface to the cfitsio library. It is designed to make the capabilities of cfitsio available to programmers working in C++. It is written in ANSI C++ and implemented using the C++ Standard Library with namespaces, exception handling, and member template functions.
  home: https://heasarc.gsfc.nasa.gov/fitsio/ccfits/
  license: CFITSIO
  license_file: License.txt
  doc_url: https://heasarc.gsfc.nasa.gov/fitsio/ccfits/html/index.html
