{% set name = "xspec-headers" %}
{% set version = "12.15.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/source/heasoft-6.35.1b.tar.gz
  sha256: beaee8e4292b249fc29722fbc71a7e4d34d25b49cb228538eb5b672c08b21132
  patches:
    - Fix_hd_install.patch  # [win]
    - Fix_BSUF_autoconf_variable.patch  # [win]

build:
  number: 0
  skip: True  # [not win]
  ignore_run_exports:
    - ucrt  # [win]
    - libgcc  # [win]
    - libstdcxx  # [win]
    - libgfortran  # [win]
    - libgfortran5  # [win]

requirements:
  build:
    - autotools_clang_conda
  host:
    - gcc_win-64
    - gxx_win-64
    - gfortran_win-64

about:
  home: https://heasarc.gsfc.nasa.gov/docs/xanadu/xspec/
  summary: An X-Ray Spectral Fitting Package
  license: Unlicense
  license_file: README.md
