{% set name = "pkg-config-is-pkgconf" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: .

build:
  number: 0
  skip: True  # [not win]

requirements:
  build:
    - vs2022_win-64
  host:
    - symlink-exe-build
  run:
    - pkgconf
  run_constrained:
    - pkg-config <0.0a0

about:
  home: https://github.com/pkgconf/pkgconf
  license: MIT
  summary: package compiler and linker metadata toolkit
  dev_url: https://github.com/pkgconf/pkgconf

extra:
  recipe-maintainers:
    - feng1m8
