{% set name = "mingw-w64-ucrt-x86_64-ccfits" %}
{% set version = "2.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: .

build:
  number: 0
  skip: True  # [not win]

requirements:
  build:
    - m2-grep
    - m2-file
    - m2-bsdtar
    - m2-autoconf
    - m2-automake-wrapper
    - m2-make
    - m2-libtool
    - feng1m8::m2-pacman

outputs:
  - name: {{ name }}
    files:
      include:
        - Library/ucrt64

about:
  summary: CCfits is an object oriented interface to the cfitsio library. It is designed to make the capabilities of cfitsio available to programmers working in C++. It is written in ANSI C++ and implemented using the C++ Standard Library with namespaces, exception handling, and member template functions.
  home: https://heasarc.gsfc.nasa.gov/fitsio/ccfits/
  license: CUSTOM
  license_file: CCfits/License.txt
  doc_url: https://heasarc.gsfc.nasa.gov/fitsio/ccfits/html/index.html

extra:
  recipe-maintainers:
    - feng1m8
