{% set name = "noblis" %}
{% set version = "1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run_constrained:
    - blis <0.0a0

about:
  license: MIT
  summary: prevents blis installation

extra:
  recipe-maintainers:
    - feng1m8
