{% set name = "latexindent" %}
{% set version = "4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/cmhughes/{{ name }}.pl/releases/download/V{{ version }}/{{ name }}.exe
    sha256: d0dfda412a3b2d43573a89b1ddce6cad7be6c3c92845e8147266c9f888fc9542
  - url: https://github.com/cmhughes/{{ name }}.pl/archive/refs/tags/V{{ version }}.tar.gz
    sha256: 09ffd1951f49f9f99d7ea52109257ce1f407d6794dd1b82754bd0b6e5b89fe3b

build:
  number: 0
  skip: True  # [not win]

about:
  home: https://github.com/cmhughes/latexindent.pl
  summary: Script to indent LaTeX code
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
