{% set name = "ucrt64-imagemagick" %}
{% set version = "7.1.1.39" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://mirror.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-imagemagick-{{ version }}-1-any.pkg.tar.zst
  sha256: 9062a489bb3b53b5b69478a339341ce12204dabc1c2611fa9978c5c4c0af9522

build:
  number: 0
  script: python %RECIPE_DIR%/build.py
  skip: true  # [not win]

requirements:
  build:
    - delvewheel
  run:
    - bzip2
    - fftw
    - fontconfig
    - freetype
    - lcms2
    - ucrt64-liblqr
    - ucrt64-libltdl
    - libpng
    - ucrt64-libraqm
    - mingw-w64-ucrt-x86_64-libwinpthread-git
    - libxml2
    - libzlib
    - mingw-w64-ucrt-x86_64-gcc-libs
  run_constrained:
    - msys2-mingw-w64-mutex * ucrt64

about:
  home: https://www.imagemagick.org/
  license: ImageMagick
  license_file: ucrt64/share/licenses/imagemagick/LICENSE
  license_url: https://spdx.org/licenses/ImageMagick.html
  summary: An image viewing/manipulation program (mingw-w64)
  dev_url: https://github.com/ImageMagick/ImageMagick

extra:
  recipe-maintainers:
    - feng1m8
