{% set name = "perl-xml-libxml" %}
{% set version = "2.0210" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-LibXML-{{ version }}.tar.gz
  sha256: a29bf3f00ab9c9ee04218154e0afc8f799bf23674eb99c1a9ed4de1f4059a48d

build:
  number: 0
  skip: true  # [not win]

requirements:
  build:
    - make
  host:
    - m2w64-gcc
    - m2w64-libxml2
    - perl 5.32
  run:
    - perl 5.32
    - m2w64-libxml2

about:
  home: https://bitbucket.org/shlomif/perl-xml-libxml
  license: Perl
  summary: 'Interface to Gnome libxml2 xml parsing and DOM library'

extra:
  recipe-maintainers:
    - feng1m8
