{% set name = "vs2022" %}
{% set version = "19.30" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [not win]

requirements:
  run:
    - vs2022_win-64
  run_constrained:
    - vs2019_win-64 <0.0a0
    - vs2017_win-64 <0.0a0
    - vs2015_win-64 <0.0a0

about:
  license: MIT
  summary: Activation and version verification of MSVC 14.30 (VS 2022 compiler)

extra:
  recipe-maintainers:
    - feng1m8
