{% set name = "vs2022" %}
{% set version = "19.30.0" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [not win]

requirements:
  run:
    - vs2022_win-64
  run_constrained:
    - vs2019_win-64 <0.0a0
    - vs2017_win-64 <0.0a0
    - vs2015_win-64 <0.0a0

about:
  license: MIT
  summary: A metapackage for pinning vs2022 as C compiler

extra:
  recipe-maintainers:
    - feng1m8
