{% set name = "xspec-devel" %}
{% set version = "12.15.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/FTP/software/conda/source/heasoft-6.35.1.tar.gz
  sha256: ec9e5b69906d13e2863d9711ce96be018cb7220d73b77cbc2c945491a29428f4
  patches:
    - Fix_hd_install.patch  # [win]
    - Fix_BSUF_autoconf_variable.patch  # [win]

build:
  number: 0
  skip: True  # [not win]
  ignore_run_exports:
    - ucrt  # [win]
    - libgcc  # [win]
    - libstdcxx  # [win]
    - libgfortran  # [win]

requirements:
  build:
    - autotools_clang_conda
  host:
    - gcc_win-64
    - gxx_win-64
    - gfortran_win-64

about:
  home: https://heasarc.gsfc.nasa.gov/docs/xanadu/xspec/
  summary: An X-Ray Spectral Fitting Package
  license: Unlicense AND MIT
  license_file: README.md
