package:
  name: m2-pacman
  version: 6.1.0.8

source:
  - url: https://mirror.msys2.org/msys/x86_64/pacman-6.1.0-8-x86_64.pkg.tar.zst
    sha256: 5c4c98a5ec6afff1a11aa77d456174c8b0e539679c01a79dd439d3fc43a98df1
    folder: binary

build:
  number: 0
  noarch: generic

requirements:
  host:
    - m2-conda-epoch
  run:
    - m2-bash >=4.2.045
    - m2-bzip2
    - m2-curl
    - m2-gettext
    - m2-gnupg
    - m2-msys2-keyring
    - m2-pacman-mirrors
    - m2-which
    - m2-zstd

about:
  home: https://www.archlinux.org/pacman/
  license: GPL-2.0-or-later
  license_url: https://spdx.org/licenses/GPL-2.0-or-later.html
  summary: A library-based package manager with dependency support (MSYS2 port)
  dev_url: https://github.com/msys2/msys2-pacman

extra:
  recipe-maintainers:
    - feng1m8
