{% set name = "ar5ivist" %}
{% set version = "0.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/dginev/ar5iv-bindings/archive/refs/tags/{{ version }}.tar.gz
  sha256: fb869ee612134f0bf6b4052a9d558131440aa40be59c81680f264147cc0f6ee7

build:
  number: 0
  skip: True  # [not win]

requirements:
  run:
    - perl-latexml
    - miktex

about:
  home: https://github.com/dginev/ar5iv-bindings
  summary: Extended LaTeXML bindings for converting the sources of arXiv.org
  license: MIT
  license_file: bindings/LICENSE
