{% set name = "perl-image-magick" %}
{% set version = "7.1.1" %}

package:
  name: {{ name }}
  version: "{{ version }}.28"

source:
  url: https://cpan.metacpan.org/authors/id/J/JC/JCRISTY/Image-Magick-{{ version }}-28.tar.gz
  sha256: bc54137346c1d45626e7075015f7d1dae813394af885457499f54878cfc19e0b

build:
  number: 0
  skip: true  # [not win]

requirements:
  build:
    - perl 5.32.*
    - make
    - feng1m8::m2-pacman
  run:
    - perl 5.32.*

outputs:
  - name: {{ name }}
    files:
      include:
        - Library/site

about:
  home: https://metacpan.org/dist/Image-Magick
  license: ImageMagick
  # license_file: LICENSE
  summary: ImageMagick PERL Extension

extra:
  recipe-maintainers:
    - feng1m8
