{% set name = "m2w64-libxml2" %}
{% set version = "2.9.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-64bit-portable.zip
  sha1: fac226b31461f2392702822052a3a5628917f857

build:
  number: 0
  script: python %RECIPE_DIR%/build.py
  skip: true  # [not win]

requirements:
  build:
    - delvewheel
  run:
    - m2w64-gcc-libs
    - m2w64-gettext
    - m2w64-xz
    - m2w64-zlib

about:
  home: http://www.xmlsoft.org/
  license: MIT
  license_file: licenses/libxml2/COPYING
  summary: XML parsing library, version 2 (mingw-w64)

extra:
  recipe-maintainers:
    - feng1m8
