{% set name = "mingw-w64-ucrt-x86_64-chealpix" %}
{% set version = "3.30.0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  path: .

build:
  number: 0
  skip: True  # [not win]

requirements:
  build:
    - m2-grep
    - m2-file
    - m2-bsdtar
    - m2-autoconf
    - m2-automake-wrapper
    - m2-make
    - m2-libtool
    - feng1m8::m2-pacman

outputs:
  - name: "{{ name }}"
    files:
      include:
        - Library/ucrt64

about:
  home: "https://sourceforge.net/projects/healpix/"
  doc_url: "http://healpix.sf.net/documentation.php"
  dev_url: "https://sourceforge.net/projects/healpix/"
  license: "GPL-2.0-or-later"
  license_family: "GPL"
  license_file: "COPYING"
  summary: "Software for pixelization, hierarchical indexation, synthesis, analysis, and visualization of data on the sphere."
  description: |
    HEALPix is a Hierarchical, Equal Area, and iso-Latitude Pixelation of
    the sphere designed to support efficiently (1) local operations on the
    pixel set, (2) a hierarchical tree structure for multi-resolution
    applications, and (3) the global Fast Spherical Harmonic transform.
    HEALPix based mathematical software meets the challenges presented 
    by high resolution and large volume data sets, such as the WMAP and
    Planck CMB mission products.

extra:
  recipe-maintainers:
    - feng1m8
