{% set name = "ismkl" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - libblas * *mkl

about:
  license: MIT
  summary: Metapackage for pinning mkl as the BLAS implementation

extra:
  recipe-maintainers:
    - feng1m8
