{% set name = "gsl-static" %}
{% set version = "2.7.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: .

build:
  number: 0
  script: python %RECIPE_DIR%/build.py
  skip: True  # [not win]

requirements:
  build:
    - conan
  run:
    - gsl =2.7

about:
  home: http://www.gnu.org/software/gsl/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: GNU Scientific Library

extra:
  recipe-maintainers:
    - feng1m8
