name: Build on Windows

run-name: ${{ github.event.inputs.package }} ${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package Name'
        required: true
        type: string
      version:
        description: 'Package Version'
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Remove Strawberry Perl
        run: rmdir /s /q C:\Strawberry

      - uses: actions/checkout@v6
        with: 
          sparse-checkout: ${{ github.event.inputs.package }}

      - uses: conda-incubator/setup-miniconda@v4
        with:
          auto-activate: true
          activate-environment: ""
          auto-update-conda: true
          conda-build-version: "*"
          channels: conda-forge,feng1m8
          conda-remove-defaults: "true"

      - run: conda build ${{ github.event.inputs.package }}

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ github.event.inputs.package }}-${{ github.event.inputs.version }}
          path: ${{ env.CONDA }}\conda-bld\win-64\*.conda
